# Generated by Django 5.1.4 on 2026-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_category_document_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Cybersecurity', 'Cybersecurity'), ('Software Engineering', 'Software Engineering'), ('Data Science', 'Data Science'), ('Biology', 'Biology'), ('Biotechnology', 'Biotechnology'), ('Medicine', 'Medicine'), ('Neuroscience', 'Neuroscience'), ('Genetics', 'Genetics'), ('Agriculture', 'Agriculture'), ('Environmental Science', 'Environmental Science'), ('Climate', 'Climate'), ('Energy', 'Energy'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Astronomy', 'Astronomy'), ('Economics', 'Economics'), ('Finance', 'Finance'), ('Business', 'Business'), ('Law', 'Law'), ('Education', 'Education'), ('Psychology', 'Psychology'), ('Sociology', 'Sociology'), ('History', 'History'), ('Philosophy', 'Philosophy'), ('Arts & Design', 'Arts & Design'), ('Literature', 'Literature'), ('Engineering', 'Engineering'), ('Legal', 'Legal'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('Research', 'Research'), ('Operations', 'Operations'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
