# Generated by Django 5.1.4 on 2026-09-27 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_document_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'ollama'), ('openai', 'openai'), ('anthropic', 'anthropic'), ('gemini', 'gemini')], default='ollama', max_length=20)),
                ('chat_model', models.CharField(blank=True, default='', max_length=120)),
                ('api_key', models.CharField(blank=True, default='', max_length=400)),
                ('base_url', models.CharField(blank=True, default='', max_length=300)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_tokens', models.IntegerField(default=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_download', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.document')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'shared_with_user')},
            },
        ),
    ]
